# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visual_MainWindow(object):
    def setupUi(self, Visual_MainWindow):
        Visual_MainWindow.setObjectName("Visual_MainWindow")
        Visual_MainWindow.resize(960, 661)
        self.centralwidget = QtWidgets.QWidget(Visual_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.webWidget = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webWidget.setObjectName("webWidget")
        self.verticalLayout_2.addWidget(self.webWidget)
        self.btnTestGlance = QtWidgets.QPushButton(self.centralwidget)
        self.btnTestGlance.setObjectName("btnTestGlance")
        self.verticalLayout_2.addWidget(self.btnTestGlance)
        self.verticalLayout_2.setStretch(0, 4)
        Visual_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Visual_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        Visual_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Visual_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Visual_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Visual_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Visual_MainWindow)

    def retranslateUi(self, Visual_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Visual_MainWindow.setWindowTitle(_translate("Visual_MainWindow", "Visual Application"))
        self.btnTestGlance.setText(_translate("Visual_MainWindow", "Test Paraview Glance"))
from PyQt5 import QtWebEngineWidgets
